codecov:
  branch: master

comment:
  layout: header, changes, diff

token: 2e9679cc-6cb5-4835-a539-4544d67ca529

coverage:
  ignore:
  - se.nrm.dina.datamodel
  - se.nrm.dina.datamodel.impl
  - dina-data-service/src/main/java/org/netbeans/rest/application/config/ApplicationConfig.java
  
  status:
    patch: false
