comment:
  layout: header, changes, diff
coverage:
  ignore:
  - dina-datamodel/*
  - dina-data-service/src/main/java/org/netbeans/rest/application/config/ApplicationConfig.java
  status:
    patch: false
